version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: pg-container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: rideshare
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - pgdata:/var/lib/postgresql/data

  mongo:
    image: mongo:6
    container_name: mongo-container
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

  app:
    build: .
    container_name: springboot-app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - mongo
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/rideshare
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/rideshareDB

volumes:
  pgdata:
  mongodata:
